kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.mkurleto.io
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
