apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parking-staging
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |
        image:
          tag: 28a307056998b935feac859a5a66f3aa0ea2a7db

        ingress:
          host: parking-staging.mkurleto.io
    repoURL: https://github.com/zbsss/parking-zones.git
    targetRevision: 28a307056998b935feac859a5a66f3aa0ea2a7db
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: parking-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
