apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parking
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |
        image:
          tag: 0987b9627bb73071f69b2373bcc2caca20d115b8

        ingress:
          host: warsawparkingzone.mkurleto.io
    repoURL: https://github.com/zbsss/parking-zones.git
    targetRevision: 0987b9627bb73071f69b2373bcc2caca20d115b8
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: parking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
