apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parking-staging
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |
        image:
          tag: 780a7a2e4e881f492f0b2bdd606d6c2804d63965

        ingress:
          host: parking-staging.mkurleto.io
    repoURL: https://github.com/zbsss/parking-zones.git
    targetRevision: 780a7a2e4e881f492f0b2bdd606d6c2804d63965
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: parking-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
