apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skincareroutine
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
      - values.staging.yaml
    repoURL: https://github.com/zbsss/skincareroutine.io.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: skincareroutine-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
