apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snippetbox
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
      - environments/prod.values.yaml
      values: |
        image:
          tag: latest
        ingress:
          enabled: true
          hosts:
            - host: snippetbox.mkurleto.io
              paths:
                - path: /
                  pathType: Prefix
    repoURL: https://github.com/zbsss/snippetbox.git
    targetRevision: main
    path: deploy/helm/snippetbox
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'
  destination:
    server: https://kubernetes.default.svc
    namespace: snippetbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
