apiVersion: v1
kind: Service
metadata:
  name: cloudflared-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudflared
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP
  selector:
    app: cloudflared
